In [290]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [291]:
import torch 

In [292]:
names = open('names.txt', 'r').read().splitlines()

In [293]:
names[:100]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn',
 'abigail',
 'emily',
 'elizabeth',
 'mila',
 'ella',
 'avery',
 'sofia',
 'camila',
 'aria',
 'scarlett',
 'victoria',
 'madison',
 'luna',
 'grace',
 'chloe',
 'penelope',
 'layla',
 'riley',
 'zoey',
 'nora',
 'lily',
 'eleanor',
 'hannah',
 'lillian',
 'addison',
 'aubrey',
 'ellie',
 'stella',
 'natalie',
 'zoe',
 'leah',
 'hazel',
 'violet',
 'aurora',
 'savannah',
 'audrey',
 'brooklyn',
 'bella',
 'claire',
 'skylar',
 'lucy',
 'paisley',
 'everly',
 'anna',
 'caroline',
 'nova',
 'genesis',
 'emilia',
 'kennedy',
 'samantha',
 'maya',
 'willow',
 'kinsley',
 'naomi',
 'aaliyah',
 'elena',
 'sarah',
 'ariana',
 'allison',
 'gabriella',
 'alice',
 'madelyn',
 'cora',
 'ruby',
 'eva',
 'serenity',
 'autumn',
 'adeline',
 'hailey',
 'gianna',
 'valentina',
 'isla',
 'eliana',
 'quinn',
 'nevaeh',
 'ivy',
 'sadie',
 'piper',
 'lydia',
 'alexa',
 'josephine',
 'emery',
 'julia'

In [365]:
char_lookup = set(''.join(names))
char_lookup
char_lookup_list = ['.'] + sorted(list(char_lookup))
lookup_dict = {s:i  for i,s in enumerate(char_lookup_list)}
lookup_dict

reverse_lookup_dict = {s:i for s,i in enumerate(char_lookup_list)}

reverse_lookup_dict

{0: '.',
 1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z'}

In [295]:
N = torch.zeros((27,27), dtype = torch.int32)
N

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],


In [296]:
for name in names:
    chars = ['.'] + list(name) + ['.']
    for ch1, ch2 in zip(chars,chars[1:]):
        bigram = (lookup_dict[ch1] ,lookup_dict[ch2])
        N[bigram]+=1

In [297]:
N

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1],
        [3983,  679,  121,  153,  384, 1271,   82,

In [298]:

g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3,generator = g)
p = p/p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [299]:
print(reverse_lookup_dict[torch.multinomial (N[0]/N[0].sum(), num_samples = 1, replacement=True, generator=g).item()])


y


In [300]:
P = N.float()
P = P / P.sum(1,keepdim = True)


In [301]:
idx = 0
name = ''
while True:
    current_row = P[idx]
    new_char = reverse_lookup_dict[torch.multinomial (P[idx], num_samples = 1, replacement=True, generator=g).item()]
    if new_char == '.':
        break
    name += new_char
    idx = lookup_dict[new_char]
name

'ayda'

In [361]:
import torch.nn.functional as F
xs, ys = [],[]

for name in names:
    chars = ['.'] + list(name) + ['.']
    for char1, char2 in zip(chars, chars[1:]):
        xs.append(lookup_dict[char1])
        ys.append(lookup_dict[char2])

xs = torch.tensor(xs)
ys = torch.tensor(ys)

print(xs.size())
print(ys.size())

W = torch.randn((27,27),generator=g,requires_grad=True)

input_idxs = torch.arange(xs.nelement())
F.one_hot(xs[1], num_classes=27).float()

torch.Size([228146])
torch.Size([228146])


tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [362]:
# GRADIENT DESCENT
for n in range(10):
    xs_encoded = F.one_hot(xs, num_classes=27).float()
    counts = (xs_encoded @ W).exp() #SOFTMAX
    probabilities = counts/counts.sum(1, keepdims = True) #SOFTMAX
    loss = - probabilities[input_idxs, ys].log().mean()
    print(loss.item())

    W.gradient = None
    loss.backward()

    W.data += -25 * W.grad

    

3.705650568008423
3.5122909545898438
3.2274997234344482
3.0145318508148193
2.8960306644439697
2.8141136169433594
2.812474012374878
2.866370677947998
2.887389659881592
2.881397247314453


In [380]:
for i in range(10):
    out = []
    idx = 0
    while True:
        xenc = F.one_hot(torch.tensor([idx]),num_classes=27).float()
        logits = xenc@W
        counts = logits.exp()
        p = counts/counts.sum(1,keepdims=True)

        idx = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()

        out.append(reverse_lookup_dict[idx])
        if  reverse_lookup_dict[idx] == '.':
            break
    print(''.join(out))

melylellelelia.
r.
annnia.
bahah.
sh.
kaerocstralen.
deria.
jah.
ckailylynnier.
za.
